[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
solc_version = '0.8.20'
remappings = ["@opensezppling/=lib/openzeppelin-contracts/"]

[profile.ci]
fuzz_runs = 2_000

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
mumbai = "${POLYGON_MUMBAI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimismTest = "${OPTIMISM_TEST_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrumTest = "${ARBITRUM_TEST_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
fantomTest = "${FANTOM_TEST_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bscTest = "${BSC_TEST_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_API_KEY}" }
optimismTest = { key = "${OPTIMISM_API_KEY}" }
arbitrum = { key = "${ARBITRUM_API_KEY}" }
arbitrumTest = { key = "${ARBITRUM_API_KEY}" }
fantom = { key = "${FATOMSCAN_API_KEY}" }
fantomTest = { key = "${FATOMSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}" }
bscTest = { key = "${BSCSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options