name: Codecov
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Change to Foundry directory
        run: cd foundry

      - name: Run Foundry Install
        run: forge install
        working-directory: foundry

      - name: Run Tests with Foundry
        run: forge test -vvv
        working-directory: foundry

      - name: Run snapshot
        run: forge snapshot
        working-directory: foundry

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Pedrojok01/PackMyNFT
